
import "../(app)/globals.css";
import AuthProvider from "@/context/AuthProvider";


export const metadata = {
  title: 'Jira Project Manager',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
